/* 客户档案（来自 客户档案_20260723172350.xlsx），离线内联。客户编号唯一。 */
var CUSTOMERS = [
  {
    "code": "CA79a1929af94f4642aa05e89114c24854",
    "name": "PureSpectrum",
    "short": "PureSpectrum",
    "dept": "PureSpectrum",
    "industry": "其他",
    "level": "",
    "source": "客户主动联系",
    "category": "",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CAcb269ea684fd4c8fb41eb113d2092dc8",
    "name": "宁波工程学院",
    "short": "宁波工程学院",
    "dept": "学院",
    "industry": "政府院校",
    "level": "",
    "source": "市场营销引进",
    "category": "",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CAbe390257fce6444d96d754c1d492c320",
    "name": "环球四维市场调查（北京）有限公司",
    "short": "环球四维市场调查（北京）有限公司",
    "dept": "舆情中心",
    "industry": "互联网",
    "level": "",
    "source": "其他",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA3be2c16b778911ecbfc90242ac120006",
    "name": "广州易察",
    "short": "广州易察",
    "dept": "执行部",
    "industry": "第三方",
    "level": "",
    "source": "自己独立开发",
    "category": "",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA1b56d3cfed4f4aa6a0842beb8f9f5ef1",
    "name": "百度风控",
    "short": "百度",
    "dept": "风控中心",
    "industry": "互联网",
    "level": "",
    "source": "客户主动联系",
    "category": "",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA3af3255508f94e12acfaa2ecaf5deb17",
    "name": "Dataspring API",
    "short": "Dataspring",
    "dept": "在线",
    "industry": "第三方",
    "level": "A级（年度合作300万以上）",
    "source": "公司资源",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA7bac4187ff304d9985db2a383ccf0cc4",
    "name": "CPX-RESEARCH",
    "short": "CPX-RESEARCH",
    "dept": "API",
    "industry": "互联网",
    "level": "D级（年度合作50万以下）",
    "source": "自己独立开发",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA901524edef7b497193dfafc3266c1cbd",
    "name": "厦门蚂蚁搬砖网络科技有限公司",
    "short": "",
    "dept": "",
    "industry": "",
    "level": "",
    "source": "市场营销引进",
    "category": "",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA0acddbea0eb647bf9ef6534972108041",
    "name": "浙江社协文化发展有限公司",
    "short": "浙江社协",
    "dept": "浙江社协",
    "industry": "",
    "level": "D级（年度合作50万以下）",
    "source": "自己独立开发",
    "category": "",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA949e7f4e9acd4d7cbd41a7e4b7c22b7f",
    "name": "上海交大",
    "short": "交大",
    "dept": "研究",
    "industry": "",
    "level": "",
    "source": "",
    "category": "",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA53809bdcc82b49e294b19a0bd9902597",
    "name": "益普索API",
    "short": "益普索",
    "dept": "API",
    "industry": "第三方",
    "level": "A级",
    "source": "内部人员推荐",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CAdcd2da28133249f98ca5af29877757da",
    "name": "环球四维市场调查（北京）有限公司",
    "short": "环球四维",
    "dept": "舆情中心",
    "industry": "互联网",
    "level": "",
    "source": "其他",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA3f122026bceb491c82982b5943a8e241",
    "name": "胡润百富",
    "short": "胡润百富",
    "dept": "市场",
    "industry": "第三方",
    "level": "C级",
    "source": "市场部引进",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CAa0bca0220cc945458869a05f22ff7403",
    "name": "API-生态批量立项-特殊",
    "short": "API-生态批量立项-特殊",
    "dept": "生态部门",
    "industry": "第三方",
    "level": "A级",
    "source": "公司资源",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA15bdb2b4665042eb80b598c87e908f9d",
    "name": "Cint API",
    "short": "Cint",
    "dept": "在线",
    "industry": "第三方",
    "level": "A级",
    "source": "公司资源",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CAa03bdc0ab2094ce083b2a0949256a24f",
    "name": "Lucid API",
    "short": "Lucid",
    "dept": "在线",
    "industry": "第三方",
    "level": "A级",
    "source": "公司资源",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA7c794362894a40459efbc725d4cac770",
    "name": "pollfish API",
    "short": "Pollfish",
    "dept": "在线",
    "industry": "第三方",
    "level": "A级",
    "source": "公司资源",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA51fb6812ddf04baf8b3e94c863f29f76",
    "name": "Dalia  API",
    "short": "Dalia Research",
    "dept": "在线",
    "industry": "第三方",
    "level": "A级",
    "source": "公司资源",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA3964016040844e9e9682bee466019695",
    "name": "Marketcube API",
    "short": "Marketcube API",
    "dept": "在线",
    "industry": "第三方",
    "level": "A级",
    "source": "公司资源",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA9e132d19ca1f471da8d3357dfacb0bc9",
    "name": "Dynata（SSI）API",
    "short": "Dynata",
    "dept": "在线",
    "industry": "第三方",
    "level": "A级",
    "source": "公司资源",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA969f3bd64afa41dbba9000bc37dd37c4",
    "name": "Dalia Research",
    "short": "Dalia Research",
    "dept": "业务部",
    "industry": "第三方",
    "level": "B级",
    "source": "公司资源",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA7d4e70f289e244aa820664b47823c633",
    "name": "Lucid Holdings, LLC",
    "short": "Lucid",
    "dept": "业务部",
    "industry": "第三方",
    "level": "B级",
    "source": "公司资源",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CAcce2d765ef794574bb7a9d5b2e4cfeee",
    "name": "Pollfish",
    "short": "Pollfish",
    "dept": "业务部",
    "industry": "第三方",
    "level": "B级",
    "source": "公司资源",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CAe84cf355c30e469f982a0deaea03bf0e",
    "name": "Market Cube",
    "short": "Market Cube",
    "dept": "业务部",
    "industry": "第三方",
    "level": "A级",
    "source": "公司资源",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA945e0c8fbe1543d2996ff1ed1d16e721",
    "name": "GMO技慕驿动",
    "short": "GMO",
    "dept": "在线",
    "industry": "第三方",
    "level": "A级",
    "source": "公司资源",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CAc1cd8013ade24698839bdd1816d48f48",
    "name": "江苏创研信息咨询有限公司",
    "short": "江苏创研",
    "dept": "业务部",
    "industry": "第三方",
    "level": "B级",
    "source": "公司资源",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA3be3d5b6778911ecbfc90242ac120006",
    "name": "Omnilnsigt",
    "short": "Omnilnsigt",
    "dept": "调研",
    "industry": "其他",
    "level": "",
    "source": "",
    "category": "",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA099a8a61a8134213ad176dd411f6022f",
    "name": "上海欧赛斯文化创意有限公司",
    "short": "OSENS",
    "dept": "市场策划",
    "industry": "互联网",
    "level": "A级",
    "source": "市场部推荐",
    "category": "成交客户",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA3be3266b778911ecbfc90242ac120006",
    "name": "Dataspring",
    "short": "Dataspring",
    "dept": "业务部",
    "industry": "",
    "level": "",
    "source": "",
    "category": "",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA3be32a85778911ecbfc90242ac120006",
    "name": "CINT",
    "short": "Cint",
    "dept": "业务部",
    "industry": "",
    "level": "",
    "source": "",
    "category": "",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA3be329cb778911ecbfc90242ac120006",
    "name": "Dalia",
    "short": "Dalia Research",
    "dept": "业务部",
    "industry": "",
    "level": "",
    "source": "",
    "category": "",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA3be3290f778911ecbfc90242ac120006",
    "name": "Marketcube",
    "short": "Marketcube",
    "dept": "业务部",
    "industry": "",
    "level": "",
    "source": "",
    "category": "",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA3be32885778911ecbfc90242ac120006",
    "name": "SSI",
    "short": "SSI",
    "dept": "业务部",
    "industry": "",
    "level": "",
    "source": "",
    "category": "",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA3be327af778911ecbfc90242ac120006",
    "name": "Lucid",
    "short": "Lucid",
    "dept": "业务部",
    "industry": "",
    "level": "",
    "source": "",
    "category": "",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA3be326f3778911ecbfc90242ac120006",
    "name": "GMO",
    "short": "GMO",
    "dept": "业务部",
    "industry": "",
    "level": "",
    "source": "",
    "category": "",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  },
  {
    "code": "CA3be25ff5778911ecbfc90242ac120006",
    "name": "江苏创研信息咨询有限公司",
    "short": "江苏创研",
    "dept": "采购",
    "industry": "",
    "level": "",
    "source": "",
    "category": "",
    "owner": "刘渝",
    "ownerDept": "数据BU"
  }
];
